version: "3.7"
name: apifornitures
services:
  mongo:
    container_name: apifornitures-mongo
    image: mongo:4
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"